https://colab.research.google.com/drive/1How_tOr6giSl6qAVWdGVjXL1lac7EvzU

1. Install and load package

In [ ]:
# Install sqldf package for running SQL queries inside R
install.packages("sqldf")

# Load sqldf library
library(sqldf)

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘gsubfn’, ‘proto’, ‘RSQLite’, ‘chron’


Loading required package: gsubfn

Loading required package: proto

Warning message:
“no DISPLAY variable so Tk is not available”
Loading required package: RSQLite

This code installs and loads sqldf, which allows SQL queries to be written directly on R data frames.

2. Load datasets from GitHub

In [ ]:
# Base GitHub raw link where all CSV files are stored
base_url <- "https://raw.githubusercontent.com/maazmohammed626-ctrl/northstar-database-analytics/refs/heads/main/northstar_dataset/"

# Load all NorthStar CSV files into R data frames
orders <- read.csv(paste0(base_url, "orders.csv"))
deliveries <- read.csv(paste0(base_url, "deliveries.csv"))
complaints <- read.csv(paste0(base_url, "complaints.csv"))
customers <- read.csv(paste0(base_url, "customers.csv"))
drivers <- read.csv(paste0(base_url, "drivers.csv"))
vehicles <- read.csv(paste0(base_url, "vehicles.csv"))
incidents <- read.csv(paste0(base_url, "incidents.csv"))
app_events <- read.csv(paste0(base_url, "app_events.csv"))
hubs <- read.csv(paste0(base_url, "hubs.csv"))

This code loads all required datasets directly from GitHub, making the notebook reproducible and linked to the submitted repository.

3. Check table structure

In [ ]:
# Display column names for each important dataset
colnames(orders)
colnames(deliveries)
colnames(complaints)
colnames(customers)
colnames(drivers)
colnames(vehicles)
colnames(incidents)
colnames(app_events)
colnames(hubs)

 [1] "order_id"              "customer_id"           "service_type"
 [4] "order_created_at"      "promised_window_hours" "pickup_zone"
 [7] "dropoff_zone"          "priority_level"        "order_value"
[10] "booking_channel"       "special_handling_flag"

 [1] "delivery_id"                   "order_id"
 [3] "driver_id"                     "vehicle_id"
 [5] "hub_id"                        "dispatch_time"
 [7] "delivery_completed_at"         "delivery_status"
 [9] "route_distance_km"             "manual_route_override_count"
[11] "proof_of_completion_missing"   "customer_rating_post_delivery"
[13] "fuel_or_charge_cost"

 [1] "complaint_id"        "customer_id"         "order_id"
 [4] "complaint_type"      "channel"             "severity"
 [7] "created_at"          "status"              "resolution_days"
[10] "compensation_amount"

[1] "customer_id"          "age"                  "home_zone"
[4] "customer_type"        "signup_date"          "loyalty_score"
[7] "app_engagement_score" "preferred_channel"    "account_status"

[1] "driver_id"        "base_zone"        "employment_type"  "years_experience"
[5] "training_score"   "driver_rating"    "shift_preference" "active_flag"

[1] "vehicle_id"         "vehicle_type"       "assigned_zone"
[4] "commission_date"    "battery_health_pct" "odometer_km"
[7] "maintenance_status" "telematics_version"

[1] "incident_id"       "delivery_id"       "incident_type"
[4] "reported_at"       "severity"          "resolution_status"
[7] "resolved_hours"

 [1] "event_id"        "customer_id"     "order_id"        "event_timestamp"
 [5] "event_type"      "session_id"      "device_type"     "zone_context"
 [9] "api_latency_ms"  "success_flag"

[1] "hub_id"         "hub_name"       "zone"           "hub_type"
[5] "capacity_score"

This step checks the available columns in each dataset so that SQL queries can be written using the correct field names.

4. Preview the main datasets

In [ ]:
# Show first six rows of key datasets
head(orders)
head(deliveries)
head(complaints)
head(hubs)

  order_id customer_id service_type order_created_at    promised_window_hours
1 O00001   C0292       Passenger    2024-08-20 14:43:00  6
2 O00002   C0459       Passenger    2024-05-14 22:16:00 24
3 O00003   C0161       Passenger    2025-09-02 14:37:00  4
4 O00004   C0520       Parcel       2025-01-11 17:15:00  2
5 O00005   C0558       Retail       2025-02-17 19:32:00 12
6 O00006   C0437       Retail       2024-08-05 04:55:00  1
  pickup_zone dropoff_zone priority_level order_value booking_channel
1 Airport     South        Medium         126.65      App
2 North       AIRPORT      Low            109.30      App
3 West        AIRPORT      High            33.50      Phone
4 RiverSide   North        Medium          10.04      App
5 Riverside   SOUTH        Low            125.58      Phone
6 CENTRAL     East         High           151.44      Web
  special_handling_flag
1 0
2 0
3 0
4 1
5 0
6 1

  delivery_id order_id driver_id vehicle_id hub_id dispatch_time
1 DL00001     O00938   D004      V056       H05    2024-06-18 10:57:00
2 DL00002     O00004   D138      V007       H02    2025-01-11 18:45:00
3 DL00003     O00639   D006      V049       H02    2025-06-02 20:39:00
4 DL00004     O00313   D116      V055       H02    2024-03-08 23:31:00
5 DL00005     O00844   D108      V034       H01    2025-09-21 11:43:00
6 DL00006     O00029   D037      V098       H03    2024-09-11 12:40:00
  delivery_completed_at      delivery_status route_distance_km
1 2024-06-19 09:05:59.904311 Failed          17.26
2 2025-01-11 17:39:00.000000 OnTime          10.34
3 2025-06-02 21:45:32.366770 OnTime           7.92
4 2024-03-09 23:30:08.103702 Delayed         16.42
5 2025-09-21 15:45:34.131056 OnTime          14.52
6 2024-09-12 17:11:52.384869 Delayed         13.84
  manual_route_override_count proof_of_completion_missing
1 1                           0
2 1                           0
3 0                           0
4 0                           0
5 1                           0
6 0                           0
  customer_rating_post_delivery fuel_or_charge_cost
1 3.07                          12.05
2 5.00                          13.41
3 4.98                           8.51
4 4.18                          13.62
5 4.18                           9.22
6 1.57                           9.58

  complaint_id customer_id order_id complaint_type channel severity
1 CP0001       C0464       O00814   AppIssue       App     High
2 CP0002       C0056       O00628   MissedPickup   Phone   Medium
3 CP0003       C0469       O00384   Delay          Chatbot High
4 CP0004       C0631       O00406   Delay          App     Medium
5 CP0005       C0535       O00154   Delay          Email   Medium
6 CP0006       C0096       O00147   Delay          App     Medium
  created_at          status           resolution_days compensation_amount
1 2025-03-30 02:36:00 Open             11              23.99
2 2024-11-07 10:05:00 Open              4              21.64
3 2024-01-02 15:47:00 Open             16              26.41
4 2025-01-14 13:07:00 AwaitingCustomer  7              23.44
5 2024-08-31 05:56:00 Resolved          1              16.18
6 2024-07-22 07:43:00 Resolved          9              18.51

  hub_id hub_name       zone    hub_type  capacity_score
1 H01    North Exchange North   Dispatch  82
2 H02    South Link     South   Dispatch  78
3 H03    East Dock      East    Warehouse 74
4 H04    West Gate      West    Dispatch  69
5 H05    Central Core   Central Control   88
6 H06    Airport Hub    Airport Dispatch  71

This gives an initial preview of the data and helps confirm that the CSV files loaded correctly.

3. Total orders by service type

In [ ]:
# Query 1: Count number of orders for each service type
q1 <- sqldf("
  SELECT service_type,
         COUNT(*) AS total_orders
  FROM orders
  GROUP BY service_type
  ORDER BY total_orders DESC
")

# Display result
q1

  service_type total_orders
1 Passenger    341
2 Parcel       308
3 Retail       297
4 Business     165
5 Medical      139

his query shows which service types generate the highest demand for NorthStar.

4. Orders by pickup and drop-off zone

In [ ]:
# Query 2: Count orders by pickup and drop-off zones
q2 <- sqldf("
  SELECT pickup_zone,
         dropoff_zone,
         COUNT(*) AS total_orders
  FROM orders
  GROUP BY pickup_zone, dropoff_zone
  ORDER BY total_orders DESC
")

# Display result
q2

    pickup_zone dropoff_zone total_orders
1   East        South        17
2   South       West         12
3   WEST        WEST         11
4   CENTRAL     RiverSide    10
5   Central     WEST         10
6   EAST        Riverside    10
7   SOUTH       Riverside    10
8   South       AIRPORT      10
9   Airport     Airport       9
10  Airport     RiverSide     9
11  EAST        South         9
12  EAST        West          9
13  RiverSide   CENTRAL       9
14  RiverSide   West          9
15  SOUTH       West          9
16  South       Airport       9
17  South       EAST          9
18  WEST        EAST          9
19  north       South         9
20  AIRPORT     WEST          8
21  CENTRAL     Airport       8
22  CENTRAL     East          8
23  Central     RiverSide     8
24  Central     West          8
25  Ctr         Central       8
26  Ctr         WEST          8
27  EAST        WEST          8
28  EAST        north         8
29  East        East          8
30  East        WEST          8
⋮   ⋮           ⋮            ⋮
223 East        north        2
224 NORTH       AIRPORT      2
225 NORTH       SOUTH        2
226 NORTH       South        2
227 North       Airport      2
228 North       Ctr          2
229 North       North        2
230 North       West         2
231 North       north        2
232 RiverSide   Airport      2
233 Riverside   Airport      2
234 Riverside   EAST         2
235 Riverside   West         2
236 Riverside   north        2
237 South       Central      2
238 South       East         2
239 WEST        North        2
240 West        East         2
241 north       Central      2
242 north       Ctr          2
243 CENTRAL     CENTRAL      1
244 Ctr         Ctr          1
245 North       CENTRAL      1
246 North       Central      1
247 North       NORTH        1
248 West        CENTRAL      1
249 West        NORTH        1
250 north       Airport      1
251 north       CENTRAL      1
252 north       NORTH        1

This query identifies the busiest movement patterns between zones, which helps understand where operational pressure is highest.

7. Average and total order value by service type

In [ ]:
# Query 3: Calculate average and total order value for each service type
q3 <- sqldf("
  SELECT service_type,
         ROUND(AVG(order_value), 2) AS avg_order_value,
         ROUND(SUM(order_value), 2) AS total_order_value
  FROM orders
  GROUP BY service_type
  ORDER BY total_order_value DESC
")

# Display result
q3

  service_type avg_order_value total_order_value
1 Passenger    96.07           32761.11
2 Parcel       87.62           26985.62
3 Retail       90.01           26734.06
4 Business     92.25           15220.43
5 Medical      87.14           12111.93

This query compares service types by revenue value, helping identify which services are financially more important.

8. Delivery status summary

In [ ]:
# Query 4: Count deliveries by delivery status
q4 <- sqldf("
  SELECT delivery_status,
         COUNT(*) AS total_deliveries
  FROM deliveries
  GROUP BY delivery_status
  ORDER BY total_deliveries DESC
")

# Display result
q4

  delivery_status total_deliveries
1 OnTime          616
2 Delayed         202
3 Failed          132

This query gives a basic view of service outcomes, including completed, delayed, or failed deliveries.

JOINED SQL QUERIES

9. Orders joined with deliveries

In [ ]:
# Query 5: Join orders with deliveries to analyse service performance
q5 <- sqldf("
  SELECT o.service_type,
         d.delivery_status,
         COUNT(*) AS total_cases,
         ROUND(AVG(d.customer_rating_post_delivery), 2) AS avg_rating,
         ROUND(AVG(d.manual_route_override_count), 2) AS avg_route_overrides,
         ROUND(AVG(d.fuel_or_charge_cost), 2) AS avg_cost
  FROM orders o
  INNER JOIN deliveries d
    ON o.order_id = d.order_id
  GROUP BY o.service_type, d.delivery_status
  ORDER BY total_cases DESC
")

# Display result
q5

   service_type delivery_status total_cases avg_rating avg_route_overrides
1  Passenger    OnTime          171         4.28       0.78
2  Parcel       OnTime          156         4.28       0.99
3  Retail       OnTime          146         4.28       0.98
4  Business     OnTime           73         4.31       1.10
5  Medical      OnTime           70         4.27       0.80
6  Passenger    Delayed          53         3.06       1.11
7  Retail       Delayed          50         3.14       0.82
8  Parcel       Delayed          49         3.10       1.37
9  Passenger    Failed           38         3.01       0.95
10 Business     Delayed          28         3.37       1.21
11 Retail       Failed           28         3.00       0.93
12 Business     Failed           25         3.01       1.36
13 Parcel       Failed           25         3.08       0.88
14 Medical      Delayed          22         2.90       0.73
15 Medical      Failed           16         3.23       1.19
   avg_cost
1  12.05
2  13.18
3  12.84
4  12.78
5  12.65
6  13.28
7  12.72
8  12.94
9  12.74
10 13.81
11 14.13
12 13.46
13 12.73
14 13.32
15 12.56

This query connects customer orders with delivery outcomes to show how each service type performs operationally.

10.Complaints joined with orders

In [ ]:
# Query 6: Join complaints with orders to analyse dissatisfaction by service type
q6 <- sqldf("
  SELECT o.service_type,
         c.complaint_type,
         c.severity,
         COUNT(*) AS complaint_count,
         ROUND(AVG(c.resolution_days), 2) AS avg_resolution_days,
         ROUND(AVG(c.compensation_amount), 2) AS avg_compensation
  FROM orders o
  INNER JOIN complaints c
    ON o.order_id = c.order_id
  GROUP BY o.service_type, c.complaint_type, c.severity
  ORDER BY complaint_count DESC
")

# Display result
q6

   service_type complaint_type    severity complaint_count avg_resolution_days
1  Retail       Delay             Medium   20               7.00
2  Passenger    Delay             Medium   14               7.36
3  Retail       MissedPickup      Medium   14               6.00
4  Parcel       DriverBehaviour   Medium   12               5.50
5  Business     Delay             Medium   10               3.70
6  Passenger    AppIssue          Medium    9               4.44
7  Parcel       Delay             Medium    8               4.50
8  Retail       AppIssue          Medium    8               6.75
9  Retail       Delay             Low       8               6.13
10 Medical      MissedPickup      Medium    7               5.71
11 Parcel       Delay             Low       7               8.29
12 Parcel       DriverBehaviour   High      7              14.71
13 Passenger    DriverBehaviour   Medium    7               3.29
14 Passenger    MissedPickup      Medium    7               6.57
15 Retail       DriverBehaviour   Medium    7               5.57
16 Parcel       MissedPickup      High      6              10.83
17 Parcel       AppIssue          Low       5               5.80
18 Parcel       Delay             High      5              14.20
19 Parcel       MissedPickup      Medium    5               4.00
20 Parcel       SupportExperience Medium    5               6.20
21 Passenger    AppIssue          Low       5               6.00
22 Passenger    Delay             High      5              11.20
23 Passenger    MissedPickup      High      5              11.00
24 Business     AppIssue          High      4              14.50
25 Business     AppIssue          Medium    4              11.00
26 Business     Delay             Low       4               4.75
27 Business     MissedPickup      Medium    4               9.50
28 Medical      Delay             High      4              11.25
29 Medical      Delay             Low       4               2.75
30 Medical      Delay             Medium    4               4.50
⋮  ⋮            ⋮                 ⋮        ⋮               ⋮
57 Passenger    Billing           Low      2                6.0
58 Passenger    MissedPickup      Low      2                3.5
59 Passenger    SupportExperience Low      2                5.0
60 Retail       Damage            High     2               12.0
61 Retail       DriverBehaviour   Low      2                6.0
62 Retail       SupportExperience Medium   2                3.5
63 Business     Billing           High     1               16.0
64 Business     Damage            High     1                7.0
65 Business     Delay             High     1               11.0
66 Business     DriverBehaviour   High     1               10.0
67 Business     MissedPickup      Low      1                5.0
68 Business     SupportExperience High     1               13.0
69 Business     SupportExperience Medium   1               16.0
70 Medical      AppIssue          Medium   1               12.0
71 Medical      Billing           Medium   1                6.0
72 Medical      Damage            Low      1                3.0
73 Medical      SupportExperience High     1               15.0
74 Medical      SupportExperience Medium   1                3.0
75 Parcel       Damage            High     1               16.0
76 Parcel       Damage            Low      1                1.0
77 Parcel       Damage            Medium   1               12.0
78 Parcel       DriverBehaviour   Low      1               14.0
79 Passenger    Damage            Low      1               10.0
80 Passenger    Damage            Medium   1                9.0
81 Passenger    DriverBehaviour   Low      1                2.0
82 Retail       AppIssue          High     1                9.0
83 Retail       AppIssue          Low      1               12.0
84 Retail       Billing           Low      1               12.0
85 Retail       SupportExperience High     1               16.0
86 Retail       SupportExperience Low      1               14.0
   avg_compensation
1  20.33
2  15.81
3  18.17
4  15.93
5  19.43
6  11.73
7  19.64
8  15.22
9   5.13
10 15.93
11 13.37
12 41.00
13 11.72
14 22.66
15 19.43
16 39.69
17 17.70
18 38.16
19 11.32
20 14.70
21 10.63
22 30.03
23 45.93
24 37.88
25 21.61
26  3.73
27 18.77
28 33.76
29  9.18
30 11.43
⋮  ⋮
57  4.82
58  3.36
59  0.00
60 35.09
61 12.34
62 18.41
63 52.03
64 57.63
65 35.62
66 14.63
67  5.70
68 26.07
69  9.98
70 14.36
71 23.97
72 18.49
73 29.11
74 17.96
75 15.85
76 11.75
77 22.87
78  0.93
79 15.62
80 11.00
81 10.53
82 35.13
83    NA
84 10.94
85 46.47
86  4.56

This query links complaints to service types, helping identify which services create the most customer dissatisfaction.

11. Deliveries joined with hubs

In [ ]:
# Query 7: Join deliveries with hubs to analyse hub and zone performance
q7 <- sqldf("
  SELECT h.zone,
         h.hub_name,
         d.delivery_status,
         COUNT(*) AS total_deliveries,
         ROUND(AVG(d.route_distance_km), 2) AS avg_distance,
         ROUND(AVG(d.fuel_or_charge_cost), 2) AS avg_cost,
         ROUND(AVG(d.customer_rating_post_delivery), 2) AS avg_rating
  FROM deliveries d
  INNER JOIN hubs h
    ON d.hub_id = h.hub_id
  GROUP BY h.zone, h.hub_name, d.delivery_status
  ORDER BY total_deliveries DESC
")

# Display result
q7

   zone      hub_name       delivery_status total_deliveries avg_distance
1  North     North Exchange OnTime          93               13.99
2  East      East Dock      OnTime          85               14.03
3  West      West Gate      OnTime          83               12.58
4  Central   Midtown Relay  OnTime          80               12.13
5  Riverside Riverside Hub  OnTime          76               14.09
6  South     South Link     OnTime          70               14.63
7  Central   Central Core   OnTime          67               15.12
8  Airport   Airport Hub    OnTime          62               14.03
9  West      West Gate      Delayed         28               16.13
10 Airport   Airport Hub    Delayed         27               14.97
11 Central   Midtown Relay  Failed          26               13.80
12 North     North Exchange Delayed         26               12.93
13 South     South Link     Delayed         26               14.27
14 Central   Central Core   Delayed         25               13.53
15 Riverside Riverside Hub  Delayed         25               16.25
16 Central   Central Core   Failed          23               12.85
17 East      East Dock      Delayed         23               14.96
18 Central   Midtown Relay  Delayed         22               14.16
19 North     North Exchange Failed          17               12.84
20 West      West Gate      Failed          16               12.74
21 Airport   Airport Hub    Failed          15               14.98
22 Riverside Riverside Hub  Failed          14               11.82
23 East      East Dock      Failed          11               17.31
24 South     South Link     Failed          10               10.72
   avg_cost avg_rating
1  12.86    4.26
2  12.59    4.21
3  12.79    4.32
4  11.40    4.32
5  12.79    4.25
6  12.45    4.30
7  13.59    4.19
8  13.14    4.43
9  14.66    3.21
10 13.60    3.10
11 12.32    3.19
12 12.29    3.03
13 12.93    3.33
14 12.87    2.89
15 13.38    3.09
16 14.85    2.93
17 12.97    3.15
18 12.10    3.11
19 12.88    2.79
20 12.51    3.00
21 13.54    3.07
22 12.80    3.33
23 13.47    2.91
24 12.42    3.19

This query compares hub and zone performance, which is important because the case study mentions that some locations perform worse than others.

12. Deliveries joined with incidents

In [ ]:
# Query 8: Join deliveries with incidents to find hidden operational problems
q8 <- sqldf("
  SELECT d.delivery_status,
         COUNT(i.incident_id) AS total_incidents,
         COUNT(DISTINCT d.delivery_id) AS total_deliveries
  FROM deliveries d
  LEFT JOIN incidents i
    ON d.delivery_id = i.delivery_id
  GROUP BY d.delivery_status
  ORDER BY total_incidents DESC
")

# Display result
q8

  delivery_status total_incidents total_deliveries
1 OnTime          191             616
2 Delayed          55             202
3 Failed           34             132

This query checks whether delivery outcomes are linked with incidents, showing hidden failures that may not be visible from delivery status alone.

13. Customer complaints and customer type

In [ ]:
colnames(customers)

[1] "customer_id"          "age"                  "home_zone"
[4] "customer_type"        "signup_date"          "loyalty_score"
[7] "app_engagement_score" "preferred_channel"    "account_status"

In [ ]:
# Query 9: Join customers with complaints using correct column name
q9 <- sqldf("
  SELECT cu.customer_type,
         c.complaint_type,
         c.severity,
         COUNT(*) AS complaint_count
  FROM customers cu
  INNER JOIN complaints c
    ON cu.customer_id = c.customer_id
  GROUP BY cu.customer_type, c.complaint_type, c.severity
  ORDER BY complaint_count DESC
")

# Display result
q9

   customer_type complaint_type    severity complaint_count
1  Consumer      Delay             Medium   45
2  Consumer      MissedPickup      Medium   28
3  Consumer      DriverBehaviour   Medium   22
4  Consumer      Delay             Low      20
5  Consumer      AppIssue          Medium   18
6  Consumer      DriverBehaviour   High     14
7  Consumer      MissedPickup      High     14
8  Consumer      AppIssue          Low      11
9  Consumer      Delay             High     11
10 Consumer      SupportExperience Medium   11
11 Consumer      MissedPickup      Low      10
12 Consumer      AppIssue          High      6
13 Consumer      Billing           Medium    6
14 Consumer      Damage            High      6
15 SME           Delay             Medium    6
16 SME           MissedPickup      Medium    6
17 Consumer      Damage            Low       5
18 Enterprise    Delay             Medium    5
19 SME           AppIssue          High      5
20 SME           Delay             Low       5
21 SME           DriverBehaviour   Medium    5
22 Enterprise    DriverBehaviour   Medium    4
23 SME           AppIssue          Medium    4
24 SME           Delay             High      4
25 Consumer      Billing           High      3
26 Consumer      DriverBehaviour   Low       3
27 Consumer      SupportExperience High      3
28 Consumer      SupportExperience Low       3
29 Enterprise    AppIssue          Medium    3
30 Enterprise    Delay             High      3
31 Enterprise    MissedPickup      Medium    3
32 Consumer      Damage            Medium    2
33 Enterprise    AppIssue          High      2
34 Enterprise    AppIssue          Low       2
35 Enterprise    Billing           Medium    2
36 Enterprise    Delay             Low       2
37 SME           AppIssue          Low       2
38 SME           Billing           Low       2
39 SME           DriverBehaviour   High      2
40 SME           SupportExperience Low       2
41 Consumer      Billing           Low       1
42 Enterprise    MissedPickup      High      1
43 Enterprise    SupportExperience Medium    1
44 SME           Billing           High      1
45 SME           Billing           Medium    1
46 SME           Damage            High      1
47 SME           Damage            Low       1
48 SME           DriverBehaviour   Low       1
49 SME           MissedPickup      High      1
50 SME           MissedPickup      Low       1

The query was updated after checking the dataset structure. The correct column name is 'customer_type' instead of 'customer_segment'. This highlights the importance of validating real dataset fields before writing SQL queries.

14. Driver performance and delivery outcomes

In [ ]:
colnames(drivers)

[1] "driver_id"        "base_zone"        "employment_type"  "years_experience"
[5] "training_score"   "driver_rating"    "shift_preference" "active_flag"

In [ ]:
# Query 10: Join drivers with deliveries using correct column
q10 <- sqldf("
  SELECT dr.employment_type,
         d.delivery_status,
         COUNT(*) AS total_deliveries,
         ROUND(AVG(d.customer_rating_post_delivery), 2) AS avg_rating,
         ROUND(AVG(d.manual_route_override_count), 2) AS avg_route_overrides
  FROM drivers dr
  INNER JOIN deliveries d
    ON dr.driver_id = d.driver_id
  GROUP BY dr.employment_type, d.delivery_status
  ORDER BY total_deliveries DESC
")

q10

  employment_type delivery_status total_deliveries avg_rating
1 FullTime        OnTime          376              4.29
2 PartTime        OnTime          158              4.31
3 FullTime        Delayed         121              3.11
4 FullTime        Failed           85              3.06
5 Contract        OnTime           82              4.22
6 PartTime        Delayed          55              3.15
7 PartTime        Failed           29              2.95
8 Contract        Delayed          26              3.06
9 Contract        Failed           18              3.17
  avg_route_overrides
1 0.97
2 0.76
3 1.08
4 1.16
5 0.99
6 1.07
7 1.00
8 1.04
9 0.50

The query was corrected after examining the drivers dataset. The correct column name is 'employment_type' instead of 'contract_type'. This step ensures accurate SQL execution based on actual dataset structure.